.TH COLLATZ "1" "January 2026" "collatz v2.0.0" "User Commands"
.SH NAME
collatz \- print Collatz sequences
.SH SYNOPSIS
.SY
.B fib
[\fI\,OPTION\/\fR]... [\fI\,TARGET\/\fR]...
.br
.YS
.SH DESCRIPTION
.B collatz
is a Collatz sequence printer.
The Collatz Conjecture is an unsolved problem in mathematics.
The sequence is defined by a piecewise function: if 2|x_n, then x_n+1 = x_n/2; else x_n+1 = 3*x_n+1.
The Conjecture is that, upon repeated iterations of this sequence, all numbers will return to the 1->4->2->1 loop.
.TP
While this program is unable to check large numbers performantly (past 10^25 has been checked in direct searchers), it does make for an interesting "toy."
Given a TARGET, print the sequence starting from the next number in the sequence.
If multiple TARGETs are given, they will be printed without any separation.
.TP
If no \fITARGET\fRs are specified on the command line, read them from standard input.
.SH OPTIONS
Mandatory options to long options are mandatory for short options too.
.TP
\fB\-l\fR, \fB\-\-loose\-exit\fR
Change the behavior of the exit status.
Normally, the program will exit non-zero if any invalid input is provided.
This flag will change the behavior such that the program will only exit non-zero if a fatal error is encountered.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only the iteration count for each input.
.TP
\fB\-s\fR, \fB\-\-silent\fR
Supress all error messages.
.TP
\fB\-V\fR, \fB\-\-verbose\fR
Write the input target to standard output also.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a short help message and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.
.PP
.SH AUTHOR
Written by Jack R. Uteg.
.SH COPYRIGHT
Copyright \(co 2026 Jack Renton Uteg.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.TP
\fBfactor(1)\fR, \fBfib(1)\fR, \fBpoly(1)\fR
